import * as bcrypt from 'bcryptjs';
import { InferInsertModel } from 'drizzle-orm';
import { Pool } from 'pg';
import { drizzle } from 'drizzle-orm/node-postgres';
import { v4 as uuidv4 } from 'uuid';

import { env } from '@/config/env.config';
import { users } from '@/modules/users/domain/users.schema';
import { employeeProfiles } from '@/modules/employees/domain/employees.schema';

if (env.NODE_ENV !== 'production') {
  const dotenv = require('dotenv');
  dotenv.config({
    path: `${process.cwd()}/.env.${env.NODE_ENV ?? 'development'}`,
  });
}

// Provided employee data
const employeesData = [
  {
    fullName: 'Momo Client',
    gender: 'male',
    department: 'Client',
    position: 'Client',
    yearsOfService: 0,
    // answers: [],
  },
  // {
  //   fullName: 'Budi Santoso',
  //   gender: 'male',
  //   department: 'Keuangan',
  //   position: 'Staff',
  //   yearsOfService: 1,
  //   answers: [
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Sering',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Sering',
  //     'Terkadang',
  //     'Tidak Pernah',
  //     'Sering',
  //     'Sering',
  //     'Sering',
  //     'Sering',
  //     'Sering',
  //     'Sering',
  //     'Sering',
  //     'Sering',
  //   ],
  // },
  // {
  //   fullName: 'Dewi Lestari',
  //   gender: 'male',
  //   department: 'Logistik',
  //   position: 'Staff',
  //   yearsOfService: 3,
  //   answers: [
  //     'Sering',
  //     'Terkadang',
  //     'Tidak Pernah',
  //     'Terkadang',
  //     'Terkadang',
  //     'Tidak Pernah',
  //     'Tidak Pernah',
  //     'Terkadang',
  //     'Tidak Pernah',
  //     'Terkadang',
  //     'Sangat Sering',
  //     'Sering',
  //     'Terkadang',
  //     'Sering',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Sangat Sering',
  //   ],
  // },
  // {
  //   fullName: 'Agus Wijaya',
  //   gender: 'female',
  //   department: 'Keuangan',
  //   position: 'Staf',
  //   yearsOfService: 9,
  //   answers: [
  //     'Tidak Pernah',
  //     'Sering',
  //     'Terkadang',
  //     'Sering',
  //     'Terkadang',
  //     'Sering',
  //     'Tidak Pernah',
  //     'Terkadang',
  //     'Tidak Pernah',
  //     'Tidak Pernah',
  //     'Sangat Sering',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Sering',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Sering',
  //   ],
  // },
  // {
  //   fullName: 'Siti Nurhaliza',
  //   gender: 'male',
  //   department: 'Keuangan',
  //   position: 'Manager',
  //   yearsOfService: 11,
  //   answers: [
  //     'Terkadang',
  //     'Sering',
  //     'Sering',
  //     'Terkadang',
  //     'Sering',
  //     'Tidak Pernah',
  //     'Terkadang',
  //     'Tidak Pernah',
  //     'Tidak Pernah',
  //     'Tidak Pernah',
  //     'Terkadang',
  //     'Terkadang',
  //     'Tidak Pernah',
  //     'Tidak Pernah',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Tidak Pernah',
  //     'Terkadang',
  //   ],
  // },
  // {
  //   fullName: 'Fajar Hidayat',
  //   gender: 'female',
  //   department: 'Sumber Daya Manusia (HRD)',
  //   position: 'Manager',
  //   yearsOfService: 7,
  //   answers: [
  //     'Tidak Pernah',
  //     'Tidak Pernah',
  //     'Tidak Pernah',
  //     'Terkadang',
  //     'Tidak Pernah',
  //     'Tidak Pernah',
  //     'Tidak Pernah',
  //     'Terkadang',
  //     'Terkadang',
  //     'Sering',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Sering',
  //     'Terkadang',
  //     'Sering',
  //     'Terkadang',
  //     'Sering',
  //     'Terkadang',
  //     'Sering',
  //   ],
  // },
  // {
  //   fullName: 'Rina Indriani',
  //   gender: 'female',
  //   department: 'Logistik',
  //   position: 'Staff',
  //   yearsOfService: 8,
  //   answers: [
  //     'Sering',
  //     'Sering',
  //     'Sering',
  //     'Sering',
  //     'Sering',
  //     'Sering',
  //     'Terkadang',
  //     'Terkadang',
  //     'Sering',
  //     'Terkadang',
  //     'Sering',
  //     'Terkadang',
  //     'Sering',
  //     'Terkadang',
  //     'Sering',
  //     'Sering',
  //     'Sering',
  //     'Sering',
  //     'Sering',
  //     'Terkadang',
  //     'Sering',
  //   ],
  // },
  // {
  //   fullName: 'Adi Prasetyo',
  //   gender: 'male',
  //   department: 'Logistik',
  //   position: 'Staf',
  //   yearsOfService: 15,
  //   answers: [
  //     'Tidak Pernah',
  //     'Terkadang',
  //     'Sangat Sering',
  //     'Sangat Sering',
  //     'Terkadang',
  //     'Sangat Sering',
  //     'Sangat Sering',
  //     'Tidak Pernah',
  //     'Tidak Pernah',
  //     'Sering',
  //     'Sering',
  //     'Sering',
  //     'Sering',
  //     'Sangat Sering',
  //     'Terkadang',
  //     'Sangat Sering',
  //     'Sangat Sering',
  //     'Sering',
  //     'Sering',
  //     'Terkadang',
  //     'Sangat Sering',
  //   ],
  // },
  // {
  //   fullName: 'Maya Sari',
  //   gender: 'female',
  //   department: 'Analisis Data',
  //   position: 'Kasie',
  //   yearsOfService: 19,
  //   answers: [
  //     'Terkadang',
  //     'Sering',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Sering',
  //     'Tidak Pernah',
  //     'Terkadang',
  //     'Terkadang',
  //     'Sering',
  //     'Terkadang',
  //     'Terkadang',
  //     'Sering',
  //     'Terkadang',
  //     'Sering',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Sangat Sering',
  //   ],
  // },
  // {
  //   fullName: 'Rizky Darmawan',
  //   gender: 'female',
  //   department: 'Analisis Data',
  //   position: 'Staf',
  //   yearsOfService: 6,
  //   answers: [
  //     'Terkadang',
  //     'Terkadang',
  //     'Sering',
  //     'Sering',
  //     'Sering',
  //     'Terkadang',
  //     'Terkadang',
  //     'Sering',
  //     'Sering',
  //     'Terkadang',
  //     'Sangat Sering',
  //     'Sering',
  //     'Terkadang',
  //     'Terkadang',
  //     'Sangat Sering',
  //     'Terkadang',
  //     'Sangat Sering',
  //     'Sering',
  //     'Sering',
  //     'Tidak Pernah',
  //     'Sangat Sering',
  //   ],
  // },
  // {
  //   fullName: 'Anita Rahayu',
  //   gender: 'female',
  //   department: 'Riset dan Pengembangan (R&D)',
  //   position: 'Staf',
  //   yearsOfService: 7,
  //   answers: [
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Tidak Pernah',
  //     'Tidak Pernah',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Sering',
  //     'Sering',
  //     'Terkadang',
  //     'Terkadang',
  //     'Sering',
  //     'Terkadang',
  //     'Sering',
  //     'Sering',
  //     'Terkadang',
  //     'Terkadang',
  //     'Sering',
  //   ],
  // },
  // {
  //   fullName: 'Indra Setiawan',
  //   gender: 'male',
  //   department: 'Riset dan Pengembangan (R&D)',
  //   position: 'Manager',
  //   yearsOfService: 7,
  //   answers: [
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Sering',
  //     'Sering',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //   ],
  // },
  // {
  //   fullName: 'Vina Oktaviani',
  //   gender: 'female',
  //   department: 'Sumber Daya Manusia (HRD)',
  //   position: 'Manager',
  //   yearsOfService: 13,
  //   answers: [
  //     'Terkadang',
  //     'Terkadang',
  //     'Tidak Pernah',
  //     'Terkadang',
  //     'Tidak Pernah',
  //     'Tidak Pernah',
  //     'Tidak Pernah',
  //     'Tidak Pernah',
  //     'Terkadang',
  //     'Terkadang',
  //     'Tidak Pernah',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Tidak Pernah',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //   ],
  // },
  // {
  //   fullName: 'Eko Nugroho',
  //   gender: 'female',
  //   department: 'Keuangan',
  //   position: 'Manager',
  //   yearsOfService: 9,
  //   answers: [
  //     'Terkadang',
  //     'Sering',
  //     'Tidak Pernah',
  //     'Terkadang',
  //     'Terkadang',
  //     'Sering',
  //     'Terkadang',
  //     'Sering',
  //     'Tidak Pernah',
  //     'Terkadang',
  //     'Sering',
  //     'Terkadang',
  //     'Tidak Pernah',
  //     'Sering',
  //     'Terkadang',
  //     'Terkadang',
  //     'Sering',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Sering',
  //   ],
  // },
  // {
  //   fullName: 'Santi Kusumawati',
  //   gender: 'female',
  //   department: 'Keuangan',
  //   position: 'Staf',
  //   yearsOfService: 6,
  //   answers: [
  //     'Tidak Pernah',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Tidak Pernah',
  //     'Sering',
  //     'Sering',
  //     'Terkadang',
  //     'Sering',
  //     'Sering',
  //     'Sering',
  //     'Sering',
  //     'Terkadang',
  //     'Terkadang',
  //     'Sering',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //   ],
  // },
  // {
  //   fullName: 'Asep Saepudin',
  //   gender: 'female',
  //   department: 'Riset dan Pengembangan (R&D)',
  //   position: 'Manager',
  //   yearsOfService: 6,
  //   answers: [
  //     'Sering',
  //     'Sering',
  //     'Terkadang',
  //     'Sering',
  //     'Terkadang',
  //     'Terkadang',
  //     'Tidak Pernah',
  //     'Terkadang',
  //     'Tidak Pernah',
  //     'Terkadang',
  //     'Terkadang',
  //     'Sering',
  //     'Terkadang',
  //     'Sering',
  //     'Terkadang',
  //     'Sering',
  //     'Sering',
  //     'Sering',
  //     'Sering',
  //     'Sering',
  //     'Sering',
  //   ],
  // },
  // {
  //   fullName: 'Nia Sara',
  //   gender: 'female',
  //   department: 'Teknologi Informasi (IT)',
  //   position: 'Staff',
  //   yearsOfService: 7,
  //   answers: [
  //     'Sering',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Tidak Pernah',
  //     'Terkadang',
  //     'Tidak Pernah',
  //     'Tidak Pernah',
  //     'Terkadang',
  //     'Terkadang',
  //     'Tidak Pernah',
  //     'Tidak Pernah',
  //     'Terkadang',
  //     'Sering',
  //     'Tidak Pernah',
  //     'Tidak Pernah',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //   ],
  // },
  // {
  //   fullName: 'Dedi Iskandar',
  //   gender: 'male',
  //   department: 'Sumber Daya Manusia (HRD)',
  //   position: 'Staf',
  //   yearsOfService: 11,
  //   answers: [
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Tidak Pernah',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Tidak Pernah',
  //     'Tidak Pernah',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //   ],
  // },
  // {
  //   fullName: 'Fitriani Anwar',
  //   gender: 'female',
  //   department: 'Teknologi Informasi (IT)',
  //   position: 'Staf',
  //   yearsOfService: 7,
  //   answers: [
  //     'Terkadang',
  //     'Tidak Pernah',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Tidak Pernah',
  //     'Tidak Pernah',
  //     'Tidak Pernah',
  //     'Terkadang',
  //     'Terkadang',
  //     'Tidak Pernah',
  //     'Terkadang',
  //     'Terkadang',
  //     'Terkadang',
  //     'Sering',
  //     'Terkadang',
  //     'Sering',
  //     'Terkadang',
  //     'Sering',
  //   ],
  // },
];

function generateEmail(fullName: string): string {
  return (
    fullName
      .toLowerCase()
      .replace(/\s+/g, '.')
      .replace(/[^a-z0-9.]/g, '')
      .replace(/\.+/g, '.')
      .replace(/^\.+|\.+$/g, '') + '@ruangdiri.com'
  );
}

function inferGender(fullName: string): 'male' | 'female' {
  const femaleIndicators = [
    'siti',
    'ni putu',
    'rr',
    'dewi',
    'indah',
    'gita',
    'atika',
    'ariani',
    'faiqah',
    'fairuz',
    'amalia',
    'ryndha',
    'meyranti',
    'syally',
    'marsha',
    'ajeng',
    'wahyu',
    'linda',
    'laely',
    'frischa',
    'ratasya',
    'zulfah',
    'dian',
    'shalu',
    'choirunisa',
    'jeane',
    'adinda',
  ];

  const lowerName = fullName.toLowerCase();

  if (femaleIndicators.some((indicator) => lowerName.includes(indicator))) {
    return 'female';
  }

  return 'male';
}

async function main() {
  console.log('🔄 Seeding employee users and profiles...');

  const pool = new Pool({
    host: env.DB_HOST,
    port: Number(env.DB_PORT),
    user: env.DB_USERNAME,
    password: env.DB_PASSWORD,
    database: env.DB_NAME,
    ssl: false,
  });

  const db = drizzle(pool, {
    schema: {
      users,
      employeeProfiles,
    },
  });

  try {
    const defaultPassword = await bcrypt.hash('ruangdiri0425', 10);
    const organizationId = '63df8b4c-3816-4c60-be3b-1b1012ff5491';

    const usersData: Array<InferInsertModel<typeof users>> = [];
    const profilesData: Array<InferInsertModel<typeof employeeProfiles>> = [];

    for (const employee of employeesData) {
      const userId = uuidv4();
      const email = generateEmail(employee.fullName);
      // Create user record
      usersData.push({
        id: userId,
        email,
        password: defaultPassword,
        fullName: employee.fullName,
        role: 'employee',
        organizationId,
        isActive: true,
        isOnboarded: false,
      });
      // Create employee profile record
      profilesData.push({
        userId,
        department: employee.department,
        position: employee.position || 'Staff',
        gender: employee.gender as 'male' | 'female',
        yearsOfService: employee.yearsOfService,
      });
    }

    await db.transaction(async (tx) => {
      await tx.insert(users).values(usersData);
      await tx.insert(employeeProfiles).values(profilesData);
    });

    console.log(
      `✅ Seeded ${usersData.length} employee users and ${profilesData.length} employee profiles`,
    );
  } catch (error) {
    console.error('❌ Error seeding employee data:', error);
    throw error;
  } finally {
    await pool.end();
    console.log('🔌 Database connection closed');
  }
}

main().catch((err) => {
  console.error('❌ Fatal error:', err);
  process.exit(1);
});
